
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    url: http://zabbix-web:8080
    access: proxy
    basicAuth: false
